"""
Admin User Markdown Export Router (TEST ONLY)

⚠️ TEST ONLY ENDPOINT — MUST NOT BE ENABLED IN PRODUCTION
⚠️ EXPOSES TEST PASSWORDS — ADMIN USE ONLY

This router exports user credentials as Markdown for testing documentation.
Reuses existing credential service from MODULE 5.4.
"""

from fastapi import APIRouter, Depends, Response

# Import existing auth dependencies
from ..services.auth_service import get_current_user, CurrentUser
from ..utils.guards import require_software_admin

# Reuse existing credential service from MODULE 5.4
from ..services.user_credentials_service import get_all_user_credentials_service


# Create router
router = APIRouter(
    prefix="/api/admin/testing",
    tags=["admin-testing"]
)


@router.get("/user-credentials-markdown")
def export_user_credentials_as_markdown(
    current_user: CurrentUser = Depends(get_current_user)
) -> Response:
    """
    Export all user credentials as a Markdown table (TEST ONLY).
    
    ⚠️ TEST ONLY — DO NOT USE IN PRODUCTION
    ⚠️ EXPOSES TEST PASSWORDS
    
    **Requires:** SOFTWARE_ADMIN role
    
    **Purpose:**
    - Generate Markdown documentation of all test accounts
    - Easy to copy/paste into testing documentation
    - Formatted table with username, role, org unit, and password
    
    **Returns:**
    Raw Markdown text (Content-Type: text/markdown)
    
    **Example Output:**
    ```markdown
    | Username | Role | Org Unit | Active | Password |
    |----------|------|----------|--------|----------|
    | sec_10_admin | SECTION_ADMIN | Emergency Dept | True | Hospital2026! |
    | dept_5_admin | DEPARTMENT_ADMIN | Medical Affairs | True | Hospital2026! |
    ```
    
    **Security Notes:**
    - Only accessible by SOFTWARE_ADMIN
    - Shows derived test passwords (not actual hashes)
    - MUST be disabled before production deployment
    """
    # Check SOFTWARE_ADMIN permission
    require_software_admin(current_user)
    
    # Get credentials from existing service (MODULE 5.4)
    credentials = get_all_user_credentials_service()
    
    # Build Markdown table
    markdown_lines = [
        "# User Credentials (TEST ONLY)",
        "",
        "⚠️ **WARNING:** These are test credentials. Do not use in production.",
        "",
        "| Username | Role | Org Unit | Active | Password |",
        "|----------|------|----------|--------|----------|"
    ]
    
    # Add each user as a table row
    for user in credentials:
        username = user.get('username', '')
        role = user.get('role') or ''
        org_unit = user.get('org_unit') or ''
        active = str(user.get('active', False))
        password = user.get('test_password') or ''
        
        # Format as markdown table row
        row = f"| {username} | {role} | {org_unit} | {active} | {password} |"
        markdown_lines.append(row)
    
    # Add footer
    markdown_lines.extend([
        "",
        "---",
        "",
        f"**Total Users:** {len(credentials)}",
        "",
        "**Generated by:** IncidentManager API (Phase 5 - Testing)",
        "",
        "⚠️ **SECURITY:** This endpoint must be disabled in production."
    ])
    
    # Join lines into single markdown string
    markdown_content = "\n".join(markdown_lines)
    
    # Return as raw markdown (not JSON)
    return Response(
        content=markdown_content,
        media_type="text/markdown",
        headers={
            "Content-Disposition": "inline; filename=user_credentials.md"
        }
    )
