"""
Admin User Markdown Export Router (TEST ONLY)

⚠️ TEST ONLY ENDPOINT — MUST NOT BE ENABLED IN PRODUCTION
⚠️ EXPOSES TEST PASSWORDS — ADMIN USE ONLY

This router exports user credentials as Markdown or Word for testing documentation.
Reuses existing credential service from MODULE 5.4.
"""

from fastapi import APIRouter, Depends, Response
from io import BytesIO
from datetime import datetime

# Import existing auth dependencies
from ..services.auth_service import get_current_user, CurrentUser
from ..utils.guards import require_software_admin, require_role
from core.constants.roles import SOFTWARE_ADMIN, COMPLAINT_SUPERVISOR

# Reuse existing credential service from MODULE 5.4
from ..services.user_credentials_service import get_all_user_credentials_service


# Create router
router = APIRouter(
    prefix="/api/admin/testing",
    tags=["admin-testing"]
)


@router.get("/user-credentials-markdown")
def export_user_credentials_as_markdown(
    current_user: CurrentUser = Depends(get_current_user)
) -> Response:
    """
    Export all user credentials as a Markdown table (TEST ONLY).
    
    ⚠️ TEST ONLY — DO NOT USE IN PRODUCTION
    ⚠️ EXPOSES TEST PASSWORDS
    
    **Requires:** SOFTWARE_ADMIN role
    
    **Purpose:**
    - Generate Markdown documentation of all test accounts
    - Easy to copy/paste into testing documentation
    - Formatted table with username, role, org unit, and password
    
    **Returns:**
    Raw Markdown text (Content-Type: text/markdown)
    
    **Example Output:**
    ```markdown
    | Username | Role | Org Unit | Active | Password |
    |----------|------|----------|--------|----------|
    | sec_10_admin | SECTION_ADMIN | Emergency Dept | True | Hospital2026! |
    | dept_5_admin | DEPARTMENT_ADMIN | Medical Affairs | True | Hospital2026! |
    ```
    
    **Security Notes:**
    - Only accessible by SOFTWARE_ADMIN
    - Shows derived test passwords (not actual hashes)
    - MUST be disabled before production deployment
    """
    # Check SOFTWARE_ADMIN permission
    require_role(current_user, [SOFTWARE_ADMIN, COMPLAINT_SUPERVISOR])
    
    # Get credentials from existing service (MODULE 5.4)
    credentials = get_all_user_credentials_service()
    
    # Build Markdown table
    markdown_lines = [
        "# User Credentials (TEST ONLY)",
        "",
        "⚠️ **WARNING:** These are test credentials. Do not use in production.",
        "",
        "| Username | Role | Org Unit | Active | Password |",
        "|----------|------|----------|--------|----------|"
    ]
    
    # Add each user as a table row
    for user in credentials:
        username = user.get('username', '')
        role = user.get('role') or ''
        org_unit = user.get('org_unit') or ''
        active = str(user.get('active', False))
        password = user.get('test_password') or ''
        
        # Format as markdown table row
        row = f"| {username} | {role} | {org_unit} | {active} | {password} |"
        markdown_lines.append(row)
    
    # Add footer
    markdown_lines.extend([
        "",
        "---",
        "",
        f"**Total Users:** {len(credentials)}",
        "",
        "**Generated by:** IncidentManager API (Phase 5 - Testing)",
        "",
        "⚠️ **SECURITY:** This endpoint must be disabled in production."
    ])
    
    # Join lines into single markdown string
    markdown_content = "\n".join(markdown_lines)
    
    # Return as raw markdown (not JSON)
    return Response(
        content=markdown_content,
        media_type="text/markdown",
        headers={
            "Content-Disposition": "inline; filename=user_credentials.md"
        }
    )


@router.get("/user-credentials-word")
def export_user_credentials_as_word(
    current_user: CurrentUser = Depends(get_current_user)
) -> Response:
    """Export all user credentials as a formal Word document. Requires SOFTWARE_ADMIN."""
    import os
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
    from docx.oxml.ns import qn
    from docx.oxml import OxmlElement

    require_role(current_user, [SOFTWARE_ADMIN, COMPLAINT_SUPERVISOR])
    credentials = get_all_user_credentials_service()

    # ── Document setup ──────────────────────────────────────────────
    doc = Document()
    sec = doc.sections[0]
    # Landscape A4
    sec.page_width, sec.page_height = sec.page_height, sec.page_width
    sec.left_margin   = Inches(0.8)
    sec.right_margin  = Inches(0.8)
    sec.top_margin    = Inches(0.7)
    sec.bottom_margin = Inches(0.7)

    # ── Helper: shade a table cell ───────────────────────────────────
    def shade_cell(cell, hex_color):
        tc   = cell._tc
        tcPr = tc.get_or_add_tcPr()
        shd  = OxmlElement('w:shd')
        shd.set(qn('w:val'),   'clear')
        shd.set(qn('w:color'), 'auto')
        shd.set(qn('w:fill'),  hex_color)
        tcPr.append(shd)

    # ── Header block: logo + title ───────────────────────────────────
    logo_path = os.path.join(
        os.path.dirname(__file__), '..', '..', 'assets', 'logo.png'
    )
    logo_path = os.path.normpath(logo_path)

    header_table = doc.add_table(rows=1, cols=2)
    header_table.style = 'Table Grid'
    lc = header_table.rows[0].cells[0]
    rc = header_table.rows[0].cells[1]

    # Logo on the left
    if os.path.exists(logo_path):
        lc_para = lc.paragraphs[0]
        lc_para.alignment = WD_ALIGN_PARAGRAPH.LEFT
        run = lc_para.add_run()
        run.add_picture(logo_path, width=Inches(1.4))
    else:
        lc.paragraphs[0].text = ''

    # Title block on the right
    shade_cell(rc, '1B3A5C')
    title_para = rc.paragraphs[0]
    title_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    t_run = title_para.add_run('System Access Credentials')
    t_run.bold      = True
    t_run.font.size = Pt(20)
    t_run.font.color.rgb = RGBColor(0xFF, 0xFF, 0xFF)

    sub_para = rc.add_paragraph()
    sub_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    s_run = sub_para.add_run('Incident & Feedback Management System')
    s_run.font.size  = Pt(11)
    s_run.font.color.rgb = RGBColor(0xB0, 0xC8, 0xE8)

    date_para = rc.add_paragraph()
    date_para.alignment = WD_ALIGN_PARAGRAPH.CENTER
    d_run = date_para.add_run(
        f'Issued: {datetime.now().strftime("%d %B %Y")}    |    Total Accounts: {len(credentials)}'
    )
    d_run.font.size  = Pt(9)
    d_run.font.color.rgb = RGBColor(0xCC, 0xDD, 0xEE)
    d_run.italic     = True

    # Remove borders from header table
    for row in header_table.rows:
        for cell in row.cells:
            tc   = cell._tc
            tcPr = tc.get_or_add_tcPr()
            tcBorders = OxmlElement('w:tcBorders')
            for side in ('top','left','bottom','right','insideH','insideV'):
                border = OxmlElement(f'w:{side}')
                border.set(qn('w:val'),  'none')
                border.set(qn('w:sz'),   '0')
                border.set(qn('w:space'),'0')
                border.set(qn('w:color'),'auto')
                tcBorders.append(border)
            tcPr.append(tcBorders)

    doc.add_paragraph()

    # ── Credentials table ────────────────────────────────────────────
    # Column order: No. | Username | Password | Role | Org Unit | Status
    table = doc.add_table(rows=1, cols=6)
    table.style   = 'Table Grid'
    table.alignment = WD_TABLE_ALIGNMENT.CENTER

    col_widths = [Inches(0.4), Inches(2.0), Inches(1.4), Inches(2.0), Inches(2.8), Inches(0.7)]
    headers    = ['#', 'Username', 'Password', 'Role', 'Org Unit', 'Active']

    # Header row — dark navy
    HEADER_BG   = '1B3A5C'
    HEADER_FG   = RGBColor(0xFF, 0xFF, 0xFF)
    ROW_ALT     = 'EAF1FB'   # light blue for alternating rows

    hdr_cells = table.rows[0].cells
    for i, (hdr, width) in enumerate(zip(headers, col_widths)):
        cell = hdr_cells[i]
        cell.width = width
        shade_cell(cell, HEADER_BG)
        para = cell.paragraphs[0]
        para.alignment = WD_ALIGN_PARAGRAPH.CENTER
        run = para.add_run(hdr)
        run.bold            = True
        run.font.size       = Pt(10)
        run.font.color.rgb  = HEADER_FG

    # Data rows
    for idx, user in enumerate(credentials, start=1):
        row_cells = table.add_row().cells
        password  = user.get('test_password') or '[secured]'
        values    = [
            str(idx),
            user.get('username', '') or '',
            password,
            user.get('role', '') or '',
            user.get('org_unit', '') or '',
            'Active' if user.get('active') else 'Inactive',
        ]
        bg = ROW_ALT if idx % 2 == 0 else 'FFFFFF'
        for i, (val, width) in enumerate(zip(values, col_widths)):
            cell = row_cells[i]
            cell.width = width
            shade_cell(cell, bg)
            para = cell.paragraphs[0]
            para.alignment = WD_ALIGN_PARAGRAPH.CENTER
            run = para.add_run(val)
            run.font.size = Pt(9)
            # Highlight password column in mono-style
            if i == 2:
                run.bold = True
                run.font.color.rgb = RGBColor(0x1B, 0x3A, 0x5C)

    # ── Footer paragraph ─────────────────────────────────────────────
    doc.add_paragraph()
    fp = doc.add_paragraph()
    fp.alignment = WD_ALIGN_PARAGRAPH.CENTER
    fr = fp.add_run(
        'This document is confidential and intended solely for authorised system administrators. '
        'Please store securely and do not distribute.'
    )
    fr.italic         = True
    fr.font.size      = Pt(8)
    fr.font.color.rgb = RGBColor(0x88, 0x88, 0x88)

    # ── Save & return ─────────────────────────────────────────────────
    file_buffer = BytesIO()
    doc.save(file_buffer)
    file_buffer.seek(0)

    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename  = f"SystemAccessCredentials_{timestamp}.docx"

    return Response(
        content=file_buffer.getvalue(),
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={"Content-Disposition": f"attachment; filename={filename}"}
    )
