"""
Admin User Markdown Export Router (TEST ONLY)

⚠️ TEST ONLY ENDPOINT — MUST NOT BE ENABLED IN PRODUCTION
⚠️ EXPOSES TEST PASSWORDS — ADMIN USE ONLY

This router exports user credentials as Markdown or Word for testing documentation.
Reuses existing credential service from MODULE 5.4.
"""

from fastapi import APIRouter, Depends, Response
from io import BytesIO
from datetime import datetime

# Import existing auth dependencies
from ..services.auth_service import get_current_user, CurrentUser
from ..utils.guards import require_software_admin

# Reuse existing credential service from MODULE 5.4
from ..services.user_credentials_service import get_all_user_credentials_service


# Create router
router = APIRouter(
    prefix="/api/admin/testing",
    tags=["admin-testing"]
)


@router.get("/user-credentials-markdown")
def export_user_credentials_as_markdown(
    current_user: CurrentUser = Depends(get_current_user)
) -> Response:
    """
    Export all user credentials as a Markdown table (TEST ONLY).
    
    ⚠️ TEST ONLY — DO NOT USE IN PRODUCTION
    ⚠️ EXPOSES TEST PASSWORDS
    
    **Requires:** SOFTWARE_ADMIN role
    
    **Purpose:**
    - Generate Markdown documentation of all test accounts
    - Easy to copy/paste into testing documentation
    - Formatted table with username, role, org unit, and password
    
    **Returns:**
    Raw Markdown text (Content-Type: text/markdown)
    
    **Example Output:**
    ```markdown
    | Username | Role | Org Unit | Active | Password |
    |----------|------|----------|--------|----------|
    | sec_10_admin | SECTION_ADMIN | Emergency Dept | True | Hospital2026! |
    | dept_5_admin | DEPARTMENT_ADMIN | Medical Affairs | True | Hospital2026! |
    ```
    
    **Security Notes:**
    - Only accessible by SOFTWARE_ADMIN
    - Shows derived test passwords (not actual hashes)
    - MUST be disabled before production deployment
    """
    # Check SOFTWARE_ADMIN permission
    require_software_admin(current_user)
    
    # Get credentials from existing service (MODULE 5.4)
    credentials = get_all_user_credentials_service()
    
    # Build Markdown table
    markdown_lines = [
        "# User Credentials (TEST ONLY)",
        "",
        "⚠️ **WARNING:** These are test credentials. Do not use in production.",
        "",
        "| Username | Role | Org Unit | Active | Password |",
        "|----------|------|----------|--------|----------|"
    ]
    
    # Add each user as a table row
    for user in credentials:
        username = user.get('username', '')
        role = user.get('role') or ''
        org_unit = user.get('org_unit') or ''
        active = str(user.get('active', False))
        password = user.get('test_password') or ''
        
        # Format as markdown table row
        row = f"| {username} | {role} | {org_unit} | {active} | {password} |"
        markdown_lines.append(row)
    
    # Add footer
    markdown_lines.extend([
        "",
        "---",
        "",
        f"**Total Users:** {len(credentials)}",
        "",
        "**Generated by:** IncidentManager API (Phase 5 - Testing)",
        "",
        "⚠️ **SECURITY:** This endpoint must be disabled in production."
    ])
    
    # Join lines into single markdown string
    markdown_content = "\n".join(markdown_lines)
    
    # Return as raw markdown (not JSON)
    return Response(
        content=markdown_content,
        media_type="text/markdown",
        headers={
            "Content-Disposition": "inline; filename=user_credentials.md"
        }
    )


@router.get("/user-credentials-word")
def export_user_credentials_as_word(
    current_user: CurrentUser = Depends(get_current_user)
) -> Response:
    """
    Export all user credentials as a Word document (TEST ONLY).
    
    ⚠️ TEST ONLY — DO NOT USE IN PRODUCTION
    ⚠️ EXPOSES TEST PASSWORDS
    
    **Requires:** SOFTWARE_ADMIN role
    
    **Purpose:**
    - Generate Word document with all test account credentials
    - Formatted table with username, role, org unit, and password
    - Easy to print or share for testing purposes
    
    **Returns:**
    Word document (.docx) file download
    
    **Security Notes:**
    - Only accessible by SOFTWARE_ADMIN
    - Shows derived test passwords (not actual hashes)
    - MUST be disabled before production deployment
    """
    from docx import Document
    from docx.shared import Inches, Pt, RGBColor
    from docx.enum.text import WD_ALIGN_PARAGRAPH
    from docx.enum.table import WD_TABLE_ALIGNMENT
    
    # Check SOFTWARE_ADMIN permission
    require_software_admin(current_user)
    
    # Get credentials from existing service (MODULE 5.4)
    credentials = get_all_user_credentials_service()
    
    # Create Word document
    doc = Document()
    
    # Title
    title = doc.add_heading('User Credentials Report', 0)
    title.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Warning
    warning = doc.add_paragraph()
    warning_run = warning.add_run('⚠️ TEST ONLY - DO NOT USE IN PRODUCTION ⚠️')
    warning_run.bold = True
    warning_run.font.color.rgb = RGBColor(255, 0, 0)
    warning.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Generation info
    doc.add_paragraph(f'Generated: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}')
    doc.add_paragraph(f'Total Users: {len(credentials)}')
    doc.add_paragraph()
    
    # Create table
    table = doc.add_table(rows=1, cols=5)
    table.style = 'Table Grid'
    table.alignment = WD_TABLE_ALIGNMENT.CENTER
    
    # Header row
    header_cells = table.rows[0].cells
    headers = ['Username', 'Role', 'Org Unit', 'Active', 'Password']
    for i, header in enumerate(headers):
        header_cells[i].text = header
        # Make header bold
        for paragraph in header_cells[i].paragraphs:
            for run in paragraph.runs:
                run.bold = True
    
    # Data rows
    for user in credentials:
        row_cells = table.add_row().cells
        row_cells[0].text = user.get('username', '') or ''
        row_cells[1].text = user.get('role', '') or ''
        row_cells[2].text = user.get('org_unit', '') or ''
        row_cells[3].text = str(user.get('active', False))
        row_cells[4].text = user.get('test_password', '') or ''
    
    # Footer
    doc.add_paragraph()
    footer = doc.add_paragraph()
    footer_run = footer.add_run('Generated by IncidentManager API - For Testing Purposes Only')
    footer_run.italic = True
    footer.alignment = WD_ALIGN_PARAGRAPH.CENTER
    
    # Save to BytesIO
    file_buffer = BytesIO()
    doc.save(file_buffer)
    file_buffer.seek(0)
    
    # Generate filename with timestamp
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"user_credentials_{timestamp}.docx"
    
    # Return as downloadable Word file
    return Response(
        content=file_buffer.getvalue(),
        media_type="application/vnd.openxmlformats-officedocument.wordprocessingml.document",
        headers={
            "Content-Disposition": f"attachment; filename={filename}"
        }
    )
