"""
📋 PHASE F — TEST F-B6 — ACTION LOG WORD GENERATOR

Tests for Word document generation.
Uses synthetic data - no database required.

Tests verify:
- Document generation succeeds
- Returns valid bytes
- Can be opened with python-docx
- Contains expected Arabic content
- Has correct table structure
"""

import pytest
from datetime import date, datetime
from io import BytesIO
from docx import Document
from backend.api_v2.services.action_log_word_generator import generate_action_log_word


# ============================================================================
# TEST DATA
# ============================================================================

@pytest.fixture
def minimal_report_data():
    """
    Minimal synthetic report data for testing.
    """
    return {
        "meta": {
            "season_id": 5,
            "season_name": "Q1 2026",
            "start_date": date(2026, 1, 1),
            "end_date": date(2026, 3, 31),
            "generated_at": date(2026, 2, 6),
            "generated_by": "Test User"
        },
        "completed_items": [
            {
                "action_item_id": 101,
                "title": "إجراء منجز",
                "assigned_to_display_name": "د. أحمد محمد",
                "org_unit_name": "قسم الطوارئ",
                "due_date": date(2026, 1, 15),
                "completed_at": datetime(2026, 1, 14, 10, 0, 0),
                "is_overdue": False,
                "days_overdue": None
            }
        ],
        "not_completed_items": [
            {
                "action_item_id": 102,
                "title": "إجراء متأخر",
                "assigned_to_display_name": "د. فاطمة علي",
                "org_unit_name": "قسم الجراحة",
                "due_date": date(2026, 1, 25),
                "completed_at": None,
                "is_overdue": True,
                "days_overdue": 12
            }
        ],
        "totals": {
            "completed_count": 1,
            "not_completed_count": 1,
            "overdue_count": 1
        }
    }


@pytest.fixture
def empty_report_data():
    """
    Report with no action items.
    """
    return {
        "meta": {
            "season_id": 5,
            "season_name": "Q1 2026",
            "start_date": date(2026, 1, 1),
            "end_date": date(2026, 3, 31),
            "generated_at": date(2026, 2, 6),
            "generated_by": "Test User"
        },
        "completed_items": [],
        "not_completed_items": [],
        "totals": {
            "completed_count": 0,
            "not_completed_count": 0,
            "overdue_count": 0
        }
    }


# ============================================================================
# TEST 1 — RETURNS BYTES
# ============================================================================

def test_returns_bytes(minimal_report_data):
    """
    Test that generator returns bytes object with reasonable size.
    """
    doc_bytes = generate_action_log_word(minimal_report_data)
    
    # Assert it's bytes
    assert isinstance(doc_bytes, bytes)
    
    # Assert reasonable size (Word docs are typically > 1KB)
    assert len(doc_bytes) > 1000
    
    print(f"✅ Generated Word document: {len(doc_bytes)} bytes")


# ============================================================================
# TEST 2 — OPENS WITH PYTHON-DOCX
# ============================================================================

def test_opens_with_python_docx(minimal_report_data):
    """
    Test that generated bytes can be opened as a valid Word document.
    """
    doc_bytes = generate_action_log_word(minimal_report_data)
    
    # Should not raise exception
    doc = Document(BytesIO(doc_bytes))
    
    # Basic validation
    assert doc is not None
    assert len(doc.paragraphs) > 0
    
    print(f"✅ Document opened successfully with {len(doc.paragraphs)} paragraphs")


# ============================================================================
# TEST 3 — TITLE PRESENT
# ============================================================================

def test_title_present(minimal_report_data):
    """
    Test that main Arabic title is present in document.
    """
    doc_bytes = generate_action_log_word(minimal_report_data)
    doc = Document(BytesIO(doc_bytes))
    
    # Find title in paragraphs
    title_found = False
    for para in doc.paragraphs:
        if "تقرير سجل الإجراءات" in para.text:
            title_found = True
            break
    
    assert title_found, "Main title 'تقرير سجل الإجراءات' not found in document"
    
    print("✅ Title 'تقرير سجل الإجراءات' found in document")


# ============================================================================
# TEST 4 — TABLES COUNT
# ============================================================================

def test_tables_count(minimal_report_data):
    """
    Test that document has at least 2 tables (completed and not completed).
    """
    doc_bytes = generate_action_log_word(minimal_report_data)
    doc = Document(BytesIO(doc_bytes))
    
    # Should have at least 2 tables
    assert len(doc.tables) >= 2, f"Expected >= 2 tables, found {len(doc.tables)}"
    
    print(f"✅ Document has {len(doc.tables)} tables")


# ============================================================================
# TEST 5 — COMPLETED TABLE ROW COUNT
# ============================================================================

def test_completed_table_row_count(minimal_report_data):
    """
    Test that completed items table has correct number of rows.
    """
    doc_bytes = generate_action_log_word(minimal_report_data)
    doc = Document(BytesIO(doc_bytes))
    
    # First table should be completed items
    completed_table = doc.tables[0]
    
    # Expected: header (1) + data rows (1) = 2
    expected_rows = 1 + len(minimal_report_data["completed_items"])
    actual_rows = len(completed_table.rows)
    
    assert actual_rows == expected_rows, \
        f"Completed table: expected {expected_rows} rows, found {actual_rows}"
    
    print(f"✅ Completed table has correct row count: {actual_rows}")


# ============================================================================
# TEST 6 — NOT COMPLETED TABLE ROW COUNT
# ============================================================================

def test_not_completed_table_row_count(minimal_report_data):
    """
    Test that not completed items table has correct number of rows.
    """
    doc_bytes = generate_action_log_word(minimal_report_data)
    doc = Document(BytesIO(doc_bytes))
    
    # Second table should be not completed items
    not_completed_table = doc.tables[1]
    
    # Expected: header (1) + data rows (1) = 2
    expected_rows = 1 + len(minimal_report_data["not_completed_items"])
    actual_rows = len(not_completed_table.rows)
    
    assert actual_rows == expected_rows, \
        f"Not completed table: expected {expected_rows} rows, found {actual_rows}"
    
    print(f"✅ Not completed table has correct row count: {actual_rows}")


# ============================================================================
# TEST 7 — PERIOD IN DOCUMENT
# ============================================================================

def test_period_in_document(minimal_report_data):
    """
    Test that period dates are displayed in document.
    """
    doc_bytes = generate_action_log_word(minimal_report_data)
    doc = Document(BytesIO(doc_bytes))
    
    # Find period text
    period_found = False
    full_text = "\n".join([para.text for para in doc.paragraphs])
    
    if "الفترة:" in full_text and "2026-01-01" in full_text and "2026-03-31" in full_text:
        period_found = True
    
    assert period_found, "Period dates not found in document"
    
    print("✅ Period dates found in document")


# ============================================================================
# TEST 8 — TOTALS IN DOCUMENT
# ============================================================================

def test_totals_in_document(minimal_report_data):
    """
    Test that totals summary is displayed.
    """
    doc_bytes = generate_action_log_word(minimal_report_data)
    doc = Document(BytesIO(doc_bytes))
    
    # Find totals text
    totals_found = False
    full_text = "\n".join([para.text for para in doc.paragraphs])
    
    if "إجمالي المنجز" in full_text or "غير المنجز" in full_text:
        totals_found = True
    
    assert totals_found, "Totals summary not found in document"
    
    print("✅ Totals summary found in document")


# ============================================================================
# TEST 9 — EMPTY REPORT GENERATES
# ============================================================================

def test_empty_report_generates(empty_report_data):
    """
    Test that empty report (no action items) generates successfully.
    """
    doc_bytes = generate_action_log_word(empty_report_data)
    doc = Document(BytesIO(doc_bytes))
    
    # Should still have structure
    assert doc is not None
    assert len(doc.paragraphs) > 0
    
    # Check for "no items" message
    full_text = "\n".join([para.text for para in doc.paragraphs])
    assert "لا توجد إجراءات غير منجزة" in full_text
    
    print("✅ Empty report generated successfully with 'no items' message")


# ============================================================================
# TEST 10 — COMPLETED TABLE HAS 6 COLUMNS
# ============================================================================

def test_completed_table_columns(minimal_report_data):
    """
    Test that completed items table has 6 columns.
    """
    doc_bytes = generate_action_log_word(minimal_report_data)
    doc = Document(BytesIO(doc_bytes))
    
    completed_table = doc.tables[0]
    
    # Check header row has 6 columns
    num_cols = len(completed_table.rows[0].cells)
    assert num_cols == 6, f"Expected 6 columns, found {num_cols}"
    
    print("✅ Completed table has 6 columns")


# ============================================================================
# TEST 11 — NOT COMPLETED TABLE HAS 6 COLUMNS
# ============================================================================

def test_not_completed_table_columns(minimal_report_data):
    """
    Test that not completed items table has 6 columns.
    """
    doc_bytes = generate_action_log_word(minimal_report_data)
    doc = Document(BytesIO(doc_bytes))
    
    not_completed_table = doc.tables[1]
    
    # Check header row has 6 columns
    num_cols = len(not_completed_table.rows[0].cells)
    assert num_cols == 6, f"Expected 6 columns, found {num_cols}"
    
    print("✅ Not completed table has 6 columns")


# ============================================================================
# TEST 12 — OVERDUE INDICATOR PRESENT
# ============================================================================

def test_overdue_indicator_present(minimal_report_data):
    """
    Test that overdue indicator appears in not completed table.
    """
    doc_bytes = generate_action_log_word(minimal_report_data)
    doc = Document(BytesIO(doc_bytes))
    
    not_completed_table = doc.tables[1]
    
    # Check data row for "نعم" (yes - overdue)
    # Row 1 is the data row (row 0 is header)
    overdue_cell_text = not_completed_table.rows[1].cells[0].text
    
    assert "نعم" in overdue_cell_text, f"Expected 'نعم' in overdue cell, found '{overdue_cell_text}'"
    assert "12" in overdue_cell_text, f"Expected '12' days in overdue cell, found '{overdue_cell_text}'"
    
    print(f"✅ Overdue indicator found: {overdue_cell_text}")


# ============================================================================
# RUN ALL TESTS
# ============================================================================

if __name__ == "__main__":
    pytest.main([__file__, "-v", "-s"])
