OPEN_STATUS_ID          = 1
IN_PROGRESS_STATUS_ID   = 2
CLOSED_STATUS_ID        = 3
DRAFT_STATUS_ID         = 4
READY_TO_SEND_STATUS_ID = 5

PREPARATION_STATUSES = {DRAFT_STATUS_ID, READY_TO_SEND_STATUS_ID}
