flowchart LR
    IncidentCaseDB --> IncidentDoctorDB
    IncidentCaseDB --> IncidentTargetDepartmentDB
    IncidentCaseDB --> IncidentFeedbackDB
    IncidentCaseDB --> FollowUpDB
    IncidentCaseDB --> ActionItemsDB
